spring.config.import=optional:file:.env[.properties]
# ===============================
# SUPABASE DATABASE CONFIG
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional
java.net.preferIPv4Stack=true

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=public
spring.flyway.schemas=public
spring.flyway.postgresql.transactional.lock=false

logging.level.org.flywaydb=INFO

# ===============================
# SECURITY - MICROSOFT ENTRA
# ===============================
entra.tenant-id=${ENTRA_TENANT_ID}

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${ENTRA_TENANT_ID}/v2.0

logging.level.org.springframework.security=INFO